# Generated by Django 6.0.4 on 2026-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='submission',
        ),
    ]
