# Generated by Django 6.0.4 on 2026-06-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0002_alter_transaction_transaction_type_cabletvpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignnumber',
            name='provider',
            field=models.CharField(default='5sim', max_length=20),
        ),
    ]
