# Generated by Django 6.0.4 on 2026-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0002_detail_delete_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.AddField(
            model_name='detail',
            name='active',
            field=models.BooleanField(default=True, help_text='are you active?'),
        ),
    ]
