# Generated by Django 6.0.4 on 2026-04-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0003_remove_detail_description_detail_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='active',
            field=models.BooleanField(help_text='are you active?'),
        ),
    ]
