# Generated by Django 6.0.4 on 2026-06-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0004_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
