# Generated by Django 6.0.4 on 2026-04-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0007_alter_detail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='user',
        ),
        migrations.AlterField(
            model_name='detail',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
