# Generated by Django 6.0.4 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mount', '0011_alter_detail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='active',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='level',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='pics',
        ),
        migrations.AddField(
            model_name='detail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
